snapchat/config/routes.rb
Rails.application.routes.draw do
  resources :annotated_images do
    member do
      post 'update_annotation'
      get 'edit_annotation'
    end
  end
  root 'welcome#home'
end

snapchat/app/models/annotated_image.rb
class AnnotatedImage < ApplicationRecord
    has_one_attached :image, dependent: :destroy
    validates :name, presence: true
  
   
    
    def self.image_valid? (image)
      allowed_types = ['image/jpeg', 'image/png', 'image/gif']
      image.image.content_type.in?(allowed_types)
    end
  
  end
   # def self.valid_annotations?(annotations)
    #   # count = 0
    #   # annotations.each do |key, value|
    #   #     count++
    #   #   return false if (key.empty? && !value.empty?) || (value.empty? && !key.empty?) || (key.empty? && value.empty?)||(count>9)
    #   # end
      
    #   # true
    # end

snapchat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

snapchat/app/controllers/annotated_images_controller.rb
class AnnotatedImagesController < ApplicationController
    before_action :set_image, only: %i[edit update show destroy update_annotation edit_annotation]
    # before_action :set_prev_and_next_image, only: [:show]
  
    def index
      @annotated_images = AnnotatedImage.all
    end
  
    def create
      @image = AnnotatedImage.new(image_params)
      @image.annotations = set_annotation
  
     if @image.save
        redirect_to annotated_images_path, notice: 'Image was successfully uploaded.'
      else
        flash[:alert] = 'Failed to save image'
        render :new
      end
    end
  
    def update
      #  byebug
      @image.annotations = set_annotation
      @image.image = params[:image] if params[:image]

      # byebug
      if img_checks
        # byebug
        redirect_to edit_annotated_image_path(@image)
      elsif @image.update(image_params) 
        # byebug
        flash[:notice] = 'image is updated successfully.'
        redirect_to annotated_images_path
      # else
      #   flash[:alert] = 'not updated'
      #   # byebug
      #   redirect_to edit_annotated_image_path(@image)
      end
    end
  
    def update_annotation
      @image.annotations = set_annotation
      
      if @image.save
        respond_to do |format|
          format.js { flash.now[:notice] = 'Annotations updated successfully.' }
        end
      # elsif
      #   respond_to do |format|
      #     format.js { flash[:alert] = 'Failed to update annotations.' }
      #   end
      end
    end
  # if !AnnotatedImage.valid_annotations? @image.annotations
  #       respond_to do |format|
  #         format.js { flash.now[:alert] = 'Keys and values must be present' }
  #       end
    def destroy
      @image.destroy
      redirect_to annotated_images_path
    end
  
    def edit_annotation; end
  
    # def show; end
  
    def edit; end
  
    private
  
    def img_checks
      if @image.name.empty?
        flash[:alert] = 'Image name cannot be empty'
        # byebug
        return true
      end
      
      unless @image.image.attached?
        flash[:alert] = 'Image is not attached'
        # byebug
        return true
      end
  
      unless AnnotatedImage.image_valid?(@image)
        flash[:alert] = 'Only image files (jpg, jpeg, png, gif) are allowed'
        return true
      end
  
  
      # unless AnnotatedImage.valid_annotations?(@image.annotations)
      #   flash[:alert] = 'Keys and values must be present'
      #   return true
      # end
  # byebug
      false
    end
  
    def image_params
      params.permit(:name, :image)
    end
  
    def set_image
      @image = AnnotatedImage.find(params[:id])
    end
  
    def set_annotation
      if params[:custom_keys] && params[:custom_values] && !params[:custom_keys].empty?
        custom_keys = params[:custom_keys]
        custom_values = params[:custom_values]
        custom_keys.zip(custom_values).to_h
      else
        {}.to_h
      end
    end
  end
  

snapchat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

snapchat/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home; end
  end
  

snapchat/app/helpers/application_helper.rb
module ApplicationHelper
end

snapchat/app/views/annotated_images/_key_value_pairs.html.erb
  
<div class="key-value-pairs" >
<% if @image.annotations.empty?%>
  <div class="key-value-pair form-row">
    <div class="col">
      <%= form.text_field "custom_keys[]",  class: "form-control key", placeholder: 'Key' %>
    </div>
    <div class="col">
      <%= form.text_field "custom_values[]",  class: "form-control value", placeholder: 'Value' %>
    </div>
    <div class="col-auto">
      <button type="button" class="btn btn-sm btn-info add-key-value">Add</button>
    </div>
    <div class="col-auto">
      <button type="button" class="btn btn-sm btn-danger remove-key-value">Remove</button>
    </div>
  <% end %>
  <%@image.annotations.each do |key,value| %>
    <div class="key-value-pair form-row">
      <div class="col">
        <%= form.text_field "custom_keys[]", value: key, class: "form-control key", placeholder: 'Key' %>
      </div>
      <div class="col">
        <%= form.text_field "custom_values[]", value: value , class: "form-control value", placeholder: 'Value' %>
      </div>
      <div class="col-auto">
        <button type="button" class="btn btn-sm btn-info add-key-value">Add</button>
      </div>
      <div class="col-auto">
        <button type="button" class="btn btn-sm btn-danger remove-key-value">Remove</button>
      </div>
    </div>
  <% end %>
    

   
</div>
   <div id = "extra-add-button">
   <button type="button" class="btn btn-sm btn-info add-key-value">Add</button>
  </div>
</div>

snapchat/app/views/annotated_images/edit.html.erb
<div class="container" style="margin-top: 50px;">
  <%= form_with(model: @annotated_image, url: annotated_image_path(@image),  method: :patch, local: true, html: { multipart: true }) do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, value: @image.name,  class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <h4>Add Annotations for Image</h4>
      <%= render partial: 'key_value_pairs', locals: { form: form, image: @image } %>
      <div class="form-group">
        <%= form.submit "Submit", class: "btn btn-primary" , style: "margin-top: 10px" %>
      </div>
    <% end %>
  </div>

snapchat/app/views/annotated_images/edit_annotation.html.erb
<%= form_with(model: @annotated_image, url: update_annotation_annotated_image_path(@image),method: :post, id: 'annotate_form',  remote: true ) do |form| %>
    <%= render partial: 'key_value_pairs', locals: { form: form, image: @image } %>
      <%= form.submit "Submit", class: "btn btn-primary mt-4", id: "save-keys" %>
  <% end %>

snapchat/app/views/annotated_images/index.html.erb
<div class="container text-center mt-4">
  <div class="row">
 <div class="col-md-12 text-left">
  <%= link_to 'back' , root_path %>
    </div>
  </div>
  <ul class="list-group">
    <% @annotated_images.each do |annotated_image| %>
    <li >
    <% if annotated_image.image.attached? %>
   <div class="row">
  <div class="col-md-2 text-left">
          <img class="image d-block w-50" id="previewImage" src="<%= url_for(annotated_image.image) %>"  alt="Image">
            </div>
     <div class="col-md-4 mt-1 text-left">
              <%= link_to annotated_image.image.filename , '#',  class: "image-link", data: { turbolinks: false, toggle: "modal", target: "#imageCarouselModal", image_id: annotated_image.id }   %>
            </div>
            <div class="col-md-6 text-right">
              <%= link_to 'Edit', edit_annotated_image_path(annotated_image), data: { turbolinks: false} %>
        <%= link_to 'Delete', annotated_image_path(annotated_image), method: :delete, data: { confirm: 'Are you sure?' },  data: { turbolinks: false} %>
            </div>
          </div>
        <%end%>
   <br><br>
      </li>
    <% end %>
  </ul>
</div>
<div class="modal fade" id="imageCarouselModal" tabindex="-1" role="dialog" aria-labelledby="imageCarouselModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
       <div class="modal-body">
    <div id="imageCarousel" class="carousel slide" data-interval="false">
      <div class="carousel-inner">
     <% @annotated_images.each_with_index do |image, index| %>
              <div class="carousel-item <%= index == 0 ? 'active' : '' %>" data-image-id="<%= image.id %>">
    <img class="image d-block w-90" id="previewImage" src="<%= url_for(image.image) %>"  alt="Image">
                <div class="d-flex justify-content-center mt-2 annotate-div-class">
             <button type="button" class="btn btn-info annotate-image-button" style="margin: 10px;"  data-toggle="modal" data-target="#annotateModal" data-image-id="<%= image.id %>">
              Annotate
         </button>
    </div>
             </div>
               <% end %>
          </div>
          <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
 </div>
   </div>
   </div>
  </div>
</div>
<div class="modal fade" id="annotateModal" tabindex="-1" role="dialog" aria-labelledby="annotateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
         <div class="modal-content">
  <div class="modal-header">
          <h5 class="modal-title" id="annotateModalLabel">Annotate Image</h5>
  <button type="button" class="close" id= "close_modal" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class= "form-body">
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>

snapchat/app/views/annotated_images/new.html.erb
<div class="container " style="margin-top: 50px;">
  <%= form_with(model: @annotated_image, url: annotated_images_path,  local: true, html: { multipart: true }) do |form| %>
    <div class="form-group">
      <%= form.label :image_name %>
      <%= form.text_field :name , class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :image_file %>
      <%= form.file_field :image, class: "form-control-file" , id: "image_upload" %>
    </div>
    <div class="form-group annotation-section" style="display: none;">
      <h4>Add Annotations for Image</h4>
      <div class="key-value-pairs">
        <div class="key-value-pair form-row">
          <div class="col">
          
            <%= form.text_field "custom_keys[]",  class: "form-control key", placeholder: 'Key',required: true %>
          </div>
          <div class="col">
            <%= form.text_field "custom_values[]",  class: "form-control value", placeholder: 'Value', required: true %>
          </div>
          <div class="col-auto">
            <button type="button"  add-key-value">Add</button>
          </div>
          <div class="col-auto">
            <button type="button"  remove-key-value">Remove</button>
          </div>
           
        </div>
      </div>
      <div id = "extra-add-button">
     <button type="button" class="btn btn-sm btn-info add-key-value">Add</button>
     <div class="form-group">
        <%= form.submit "Submit" %>
      </div>
    </div>
      <div class="form-group">
        <%= form.submit "Submit" %>
      </div>

    <% end %>
  </div>

snapchat/app/views/annotated_images/update_annotation.js.erb
<% if flash[:notice] %>
    $('#annotateModal .modal-body').prepend(
        '<div class="alert alert-success">' +
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
        '<span aria-hidden="true">&times;</span>' +
        '</button>' +
        '<%= j flash[:notice] %>' +
        '</div>'
      );
<% elsif flash[:alert] %>
  $('#annotateModal .modal-body').prepend(
        '<div class="alert alert-danger alert-dismissible">' +
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
        '<span aria-hidden="true">&times;</span>' +
        '</button>' +
        '<%= j flash[:alert] %>' +
        '</div>'
      );
<% end %>

snapchat/app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

snapchat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgAnnotations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'annotations' %>
<%= javascript_pack_tag 'index' %>
<%= javascript_pack_tag 'new' %>



  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

snapchat/app/views/welcome/home.html.erb
<div class="container-fluid vh-50 d-flex justify-content-center " id = "home_container">
  <div class="center-container p-4 rounded border">
    
    <%= link_to 'View images', annotated_images_path ,data: { turbolinks: false} %>
    <%= link_to 'Upload image', new_annotated_image_path,   data: { turbolinks: false} %>
  </div>
</div>